version: "3.9"

services:
  bot:
    build: .
    container_name: imgsquarefit-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
